### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by rfyiamcool** [agoragames/kairos#60]
[root@li568-252 kairos]# vim kairos/timeseries.py
[root@li568-252 kairos]# python z.py
Traceback (most recent call last):
  File "z.py", line 1, in <module>
    from kairos import Timeseries
  File "/root/kairos/kairos/__init__.py", line 9, in <module>
    from .timeseries import Timeseries
  File "/root/kairos/kairos/timeseries.py", line 878
    data = { k:v/float(step_size) for k,v in data.items() }
                                    ^
SyntaxError: invalid syntax

**Comment by awestendorf** [comment]
Yeah, python 2.6 isn't supported at this time. Though py3 support is lacking, that's the target, so newer syntax is used.
